### PR TITLE
Add TUe trashbin and fix orientation of the couches

### PR DESCRIPTION
**Pull request by MatthijsBurgh**

### CODE REVIEW

**Comment by PetervDooren** [comment]
What was fixed about the couches?

**Comment by P-ict0** [comment]
> What was fixed about the couches? 

No, the tests still say "'Arm' object has no attribute 'gripper_position_detector'"

**Comment by MatthijsBurgh** [comment]
> What was fixed about the couches?

We have the undocumented convention that the x-axis should be facing forward.

This is important for fitting.

**Comment by PetervDooren** [comment]
#TODO document undocumented convention. Positive x axis is the front

**Review by PetervDooren — APPROVED** [review]

**Pull request merged**
