### PR TITLE
removed floor of robotics testlabs sdf

### PR DESCRIPTION
**Pull request by KevinDang74**

### CODE REVIEW

**Comment by LoyVanBeek** [comment]
Nice, you found it then. Which other model does provide  a floor now? (because we will need one)

**Comment by MatthijsBurgh** [comment]
Why do we need a floor?

**Comment by LoyVanBeek** [comment]
Because physics, that's why ;-). Otherwize, you just fall and there is nothing to have friction with in Gazebo.

**Comment by MatthijsBurgh** [comment]
I think the heightmap also 'has' a floor.

**Pull request merged**
